package view;

import control.Controlador;
import control.MenuFactory;
import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowFocusListener;
import java.util.List;
import javax.swing.JMenuBar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Loja;
import model.Produto;
import model.Usuario;
import view.menus.admin.BarraDeMenuAdmin;
import view.menus.admin.PanelMenuAdmin;
import view.menus.atendente.BarraDeMenuAtendente;
import view.menus.atendente.PanelMenuAtendente;

/**
 *
 * @author Elieser
 */
public class FormPrincipal extends javax.swing.JFrame implements View {

    private Loja loja = new Loja();
    private FormLogin formDeLogin;
    private Controlador controlador;
    private MenuFactory menuFactory;

    public FormPrincipal() {
        super("Sistema de vendas");
        initComponents();
        setSize(700, 500);
        setLocationRelativeTo(null);

        formDeLogin = new FormLogin(this);
        formDeLogin.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosed(WindowEvent e) {
                System.exit(0);
            }
        });
    }

    @Override
    public void buscaNaoEncontrada() {
        JOptionPane.showMessageDialog(rootPane, "Nenhum produto encontrado!");
    }

    @Override
    public String buscarProduto() {
        return JOptionPane.showInputDialog(rootPane, "Digite o termo de busca:");
    }

    @Override
    public void erroBusca() {
        JOptionPane.showMessageDialog(rootPane, "Erro na busca!");
    }

    @Override
    public void exibirProdutos(List<Produto> produtos) {
    }

    @Override
    public void semProdutosCadastrados() {
        JOptionPane.showMessageDialog(rootPane, "Nenhum produto cadastrado!");
    }

    @Override
    public void exibeFormularioDeLogin() {
        if (!this.isVisible()) {
            this.setVisible(true);
        }
        if (!formDeLogin.isVisible()) {
            formDeLogin.setLocationRelativeTo(this);
            formDeLogin.setVisible(true);
        }
    }

    @Override
    public void adicionaListenerNoFormDeLogin(WindowFocusListener listener) {
        formDeLogin.addWindowFocusListener(listener);
    }

    @Override
    public void setMenuFactory(MenuFactory menuFactory) {
        this.menuFactory = menuFactory;
    }
    
    @Override
    public void recriaInterface() {
        JMenuBar barraDeMenu = menuFactory.createMenuBar();
        JPanel menuLateral = menuFactory.createSideMenu(controlador);

        this.setJMenuBar(barraDeMenu);

        scrollDoMenu.getViewport().add(menuLateral);

        //ajusta tamanho do scrollPanel onde é colocado o menu
        scrollDoMenu.setPreferredSize(new Dimension(200, 32000));
        scrollDoMenu.setMinimumSize(scrollDoMenu.getPreferredSize());
        revalidate(); //atualiza o desenho dos componentes na tela
    }

    public Controlador getControlador() {
        return controlador;
    }

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollDoMenu = new javax.swing.JScrollPane();
        painelDoConteudo = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        scrollDoMenu.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu"));
        scrollDoMenu.setMaximumSize(new java.awt.Dimension(150, 32767));
        scrollDoMenu.setMinimumSize(new java.awt.Dimension(150, 42));
        scrollDoMenu.setPreferredSize(new java.awt.Dimension(150, 100));
        getContentPane().add(scrollDoMenu);

        painelDoConteudo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        painelDoConteudo.setLayout(new java.awt.CardLayout());
        getContentPane().add(painelDoConteudo);

        menuBar.setPreferredSize(new java.awt.Dimension(0, 30));
        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel painelDoConteudo;
    private javax.swing.JScrollPane scrollDoMenu;
    // End of variables declaration//GEN-END:variables
}
