one:
	g++ main.cpp -D _USE_MATH_DEFINES -o sfml -std=c++11 -lsfml-graphics -lsfml-window -lsfml-system
	
two:
	g++ main2.cpp -D _USE_MATH_DEFINES -o sfml -std=c++11 -lsfml-graphics -lsfml-window -lsfml-system 

three:
	g++ main3.cpp -D _USE_MATH_DEFINES -o sfml -std=c++11 -lsfml-graphics -lsfml-window -lsfml-system 

four:
	g++ main4.cpp -D _USE_MATH_DEFINES -o sfml -std=c++11 -lsfml-graphics -lsfml-window -lsfml-system 
