planetarium:
	g++ planetarium.cpp -o planetarium -std=c++11 -lsfml-graphics -lsfml-window -lsfml-system

events:
	g++ sfml_events.cpp -o sfml_events -std=c++11 -lsfml-graphics -lsfml-window -lsfml-system
